source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

source/api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import AddFavoriteView, RemoveFavoritesView

app_name = 'api'

urlpatterns = [
    path('add_favorites/<int:pk>/', AddFavoriteView.as_view(), name='add_favorites'),
    path('remove_favorites/<int:pk>/', RemoveFavoritesView.as_view(), name='remove_favorites'),

]

source/main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api.urls')),
    path('', include('webapp.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

source/accounts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from uuid import uuid4
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now
from datetime import timedelta


TOKEN_TYPE_REGISTER = 'register'
TOKEN_TYPE_PASSWORD_RESET = 'password_reset'
TOKEN_TYPE_CHOICES = (
    (TOKEN_TYPE_REGISTER, 'Регистрация'),
    (TOKEN_TYPE_PASSWORD_RESET, 'Восстановление пароля')
)


class AuthToken(models.Model):
    token = models.UUIDField(verbose_name='Токен', default=uuid4)
    user: AbstractUser = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                                           related_name='tokens', verbose_name='Пользователь')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    life_days = models.IntegerField(default=7, verbose_name='Срок действия (в днях)')
    type = models.CharField(max_length=20, choices=TOKEN_TYPE_CHOICES,
                            default=TOKEN_TYPE_REGISTER, verbose_name='Тип токена')

    @classmethod
    def get_token(cls, token):
        try:
            return cls.objects.get(token=token)
        except cls.DoesNotExist:
            return None

    def is_alive(self):
        return (self.created_at + timedelta(days=self.life_days)) >= now()

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name = 'Аутентификационный токен'
        verbose_name_plural = 'Аутентификационные токены'


class Profile(models.Model):
    user: AbstractUser = models.OneToOneField(get_user_model(), related_name='profile',
                                              on_delete=models.CASCADE, verbose_name='Пользователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.conf import settings
from django import forms
from django.contrib.auth import get_user_model

from .models import AuthToken, Profile, TOKEN_TYPE_PASSWORD_RESET


class MyUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = ['username', 'password1', 'password2',
                  'first_name', 'last_name', 'email']

    def save(self, commit=True):
        if settings.ACTIVATE_USERS_EMAIL:
            user: AbstractUser = super().save(commit=False)
            user.is_active = False
            if commit:
                user.save()
                token = self.create_token(user)
                self.send_email(user, token)
        else:
            user = super().save(commit=commit)
            Profile.objects.create(user=user)
        return user

    # def save(self, commit=True):
    #     user = super().save(commit=commit)
    #     Profile.objects.create(user=user)
    #     return user

    def create_token(self, user):
        return AuthToken.objects.create(user=user)

    def send_email(self, user, token):
        if user.email:
            subject = 'Вы создали учётную запись на сайте "Мой Блог"'
            link = settings.BASE_HOST + reverse('accounts:activate', kwargs={'token': token.token})
            message = f'''Здравствуйте, {user.username}!
Вы создали учётную запись на сайте "Мой Блог"
Активируйте её, перейдя по ссылке {link}.
Если вы считаете, что это ошибка, просто игнорируйте это письмо.'''
            html_message = f'''Здравствуйте, {user.username}!
Вы создали учётную запись на сайте "Мой Блог"
Активируйте её, перейдя по ссылке <a href="{link}">{link}</a>.
Если вы считаете, что это ошибка, просто игнорируйте это письмо.'''
            try:
                user.email_user(subject, message, html_message=html_message)
            except Exception as e:
                print(e)


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ['first_name', 'last_name', 'email']
        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}


class ProfileChangeForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user']


class SetPasswordForm(forms.ModelForm):
    password = forms.CharField(label="Новый пароль", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput, strip=False)

    def clean_password_confirm(self):
        password = self.cleaned_data.get("password")
        password_confirm = self.cleaned_data.get("password_confirm")
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError('Пароли не совпадают!')
        return password_confirm

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm']


class PasswordChangeForm(SetPasswordForm):
    old_password = forms.CharField(label="Старый пароль", strip=False, widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.instance.check_password(old_password):
            raise forms.ValidationError('Старый пароль неправильный!')
        return old_password

    class Meta:
        model = get_user_model()
        fields = ['password', 'password_confirm', 'old_password']


class PasswordResetEmailForm(forms.Form):
    email = forms.EmailField(required=True, label='Email')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        User = get_user_model()
        if User.objects.filter(email=email).count() == 0:
            raise ValidationError('Пользователь с таким email-ом не зарегистрирован')
        return email

    def send_email(self):
        User = get_user_model()
        email = self.cleaned_data.get('email')
        user = User.objects.filter(email=email).first()
        token = AuthToken.objects.create(user=user, life_days=3, type=TOKEN_TYPE_PASSWORD_RESET)

        subject = 'Вы запросили восстановление пароля для учётной записи на сайте "Мой Блог"'
        link = settings.BASE_HOST + reverse('accounts:password_reset', kwargs={'token': token.token})
        message = f'''Ваша ссылка для восстановления пароля: {link}.
Если вы считаете, что это ошибка, просто игнорируйте это письмо.'''
        html_message = f'''Ваша ссылка для восстановления пароля: <a href="{link}">{link}</a>.
Если вы считаете, что это ошибка, просто игнорируйте это письмо.'''
        try:
            user.email_user(subject, message, html_message=html_message)
        except Exception as e:
            print(e)


class PasswordResetForm(SetPasswordForm):
    pass

source/accounts/views.py
from django.contrib.auth import get_user_model, login, update_session_auth_hash
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import PasswordChangeView, LogoutView
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.generic import View, FormView, DetailView, CreateView, UpdateView
from django.conf import settings

from accounts.forms import MyUserCreationForm, UserChangeForm, ProfileChangeForm, \
    PasswordChangeForm, PasswordResetEmailForm, PasswordResetForm
from .models import AuthToken, Profile




class RegisterView(CreateView):
    model = User
    template_name = 'user_create.html'
    form_class = MyUserCreationForm

    def form_valid(self, form):
        user = form.save()
        if settings.ACTIVATE_USERS_EMAIL:
            return redirect('webapp:index')
        else:
            login(self.request, user)
            return redirect(self.get_success_url())

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if not next_url:
            next_url = self.request.POST.get('next')
        if not next_url:
            next_url = reverse('webapp:index')
        return next_url


class RegisterActivateView(View):
    def get(self, request, *args, **kwargs):
        token = AuthToken.get_token(self.kwargs.get('token'))
        if token:
            if token.is_alive():
                self.activate_user(token)
            token.delete()
        return redirect('webapp:index')

    def activate_user(self, token):
        user = token.user
        user.is_active = True
        user.save()
        Profile.objects.create(user=user)
        login(self.request, user)


class UserDetailView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'
    paginate_related_by = 5
    paginate_related_orphans = 0

    def get_context_data(self, **kwargs):
        # articles = self.object.articles.order_by('-created_at')
        # paginator = Paginator(articles, self.paginate_related_by, orphans=self.paginate_related_orphans)
        # page_number = self.request.GET.get('page', 1)
        # page = paginator.get_page(page_number)
        # kwargs['page_obj'] = page
        # kwargs['articles'] = page.object_list
        # kwargs['is_paginated'] = page.has_other_pages()
        # if self.object == self.request.user:   # на странице пользователя показываем
        #     kwargs['show_mass_delete'] = True  # массовое удаление только владельцу
        return super().get_context_data(**kwargs)


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = 'user_change.html'
    context_object_name = 'user_obj'

    def test_func(self):
        return self.request.user == self.get_object()

    def get_context_data(self, **kwargs):
        if 'profile_form' not in kwargs:
            kwargs['profile_form'] = self.get_profile_form()
        return super().get_context_data(**kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        profile_form = self.get_profile_form()
        if form.is_valid() and profile_form.is_valid():
            return self.form_valid(form, profile_form)
        else:
            return self.form_invalid(form, profile_form)

    def form_valid(self, form, profile_form):
        form.save()
        profile_form.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, profile_form):
        context = self.get_context_data(form=form, profile_form=profile_form)
        return self.render_to_response(context)

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})

    def get_profile_form(self):
        form_kwargs = {'instance': self.object.profile}
        if self.request.method == 'POST':
            form_kwargs['data'] = self.request.POST
            form_kwargs['files'] = self.request.FILES
        return ProfileChangeForm(**form_kwargs)

        # if self.request.method == 'POST':
        #     form = ProfileChangeForm(instance=self.object, data=self.request.POST, 
        #                                 files=self.request.FILES)
        # else:
        #     form = ProfileChangeForm(instance=self.object)
        # return form


class UserPasswordChangeView(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    template_name = 'user_password_change.html'
    form_class = PasswordChangeForm
    context_object_name = 'user_obj'

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        user = form.save()
        update_session_auth_hash(self.request, user)
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


# class UserPasswordChangeView(PasswordChangeView):
#     template_name = 'user_password_change.html'
#
#     def get_success_url(self):
#         return reverse('accounts:detail', kwargs={'pk': self.request.user.pk})


class UserPasswordResetEmailView(FormView):
    form_class = PasswordResetEmailForm
    template_name = 'password_reset_email.html'
    success_url = reverse_lazy('webapp:index')

    def form_valid(self, form):
        form.send_email()
        return super().form_valid(form)


class UserPasswordResetView(UpdateView):
    model = User
    form_class = PasswordResetForm
    template_name = 'password_reset.html'
    success_url = reverse_lazy('accounts:login')

    def get_object(self, queryset=None):
        token = self.get_token()
        if token and token.is_alive():
            return token.user
        raise Http404('Ссылка не существует или её срок действия истёк')

    def form_valid(self, form):
        token = self.get_token()
        token.delete()
        return super().form_valid(form)

    def get_token(self):
        return AuthToken.get_token(self.kwargs.get('token'))

source/accounts/templates/password_reset.html
{% extends 'base.html' %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
    <h1>Восстановление пароля</h1>
    {% include 'partial/form.html' with form_method="post" %}
{% endblock %}

source/accounts/templates/password_reset_email.html
{% extends 'base.html' %}

{% block title %}Восстановление пароля{% endblock %}

{% block content %}
    <h1>Восстановление пароля</h1>
    {% url "accounts:password_reset_email" as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method="post" %}
{% endblock %}

source/accounts/templates/user_change.html
{% extends 'base.html' %}

{% block title %}Редактировать пользователя{% endblock %}

{% block menu %}
    <li><a href="{% url "accounts:detail" user_obj.pk %}">Назад</a></li>
    <li><a href="{% url "accounts:password_change" %}">Смена пароля</a></li>
{% endblock %}

{% block content %}
    <h1>Поменять личные данные</h1>
    <form action="{% url 'accounts:change' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'partial/form.html' with form=form fields_only=True %}
        {% include 'partial/form.html' with form=profile_form fields_only=True %}
        <br>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

source/accounts/templates/user_create.html
{% extends 'base.html' %}

{% block title %}Регистрация{% endblock %}

{% block auth_menu %}
    {% with request.GET.next as next_url %}
        <li><a href="{% url 'accounts:login' %}{% if next_url %}?next={{ next_url }}{% endif %}">Login</a></li>
        <li><a href="{% url 'accounts:create' %}{% if next_url %}?next={{ next_url }}{% endif %}">Sign Up</a></li>
    {% endwith %}
{% endblock %}

{% block content %}
    <h1>Регистрация</h1>
    {% include 'partial/form.html' with form_method='post' button_text="Зарегистрироваться" %}
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}

{% block title %}Пользователь{% endblock %}

{% block menu %}
    {% if request.user == user_obj %}
        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:change' user_obj.pk %}">Редактировать</a></li>
        <<li class="nav-item"><a class="nav-link" href="{% url "accounts:password_change" %}">Смена пароля</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <h1>Личная страница пользователя {{ user_obj.get_full_name|default:user_obj.username }}</h1>
{#    {% if user_obj.user_favorites.all.len > 0 %}#}

{#    {% endif %}#}
    <p>Имя пользователя: {{ user_obj.username }}</p>
    <p>Имя: {{ user_obj.first_name }}</p>
    <p>Фамилия: {{ user_obj.last_name }}</p>
    <p>Дата рождения: {{ user_obj.profile.birth_date|date:'d.m.Y' }}</p>
    <p>Почта: {{ user_obj.email }}</p>
        <p>Избранные фото:</p>
        {% for favorites in user_obj.user_favorites.all %}
        <img class="avatar" src="{{ favorites.photo.image.url }}" width="250" height="250" alt="user picture">
                        <h5 class="card-title">{{ favorites.photo.author }}</h5>
                <p class="card-text">{{ favorites.photo.signature }}</p>
                <p class="card-text"><small class="text-muted">{{ favorites.photo.created_at }}</small></p>
        {% empty %}
            <p>Нет избраных фото</p>
    {% endfor %}

{#    <h2 class="text-center clear">Статьи автора:</h2>#}
{#    {% include 'partial/article_list.html' %}#}
{% endblock %}

source/accounts/templates/user_password_change.html
{% extends 'base.html' %}

{% block title %}Смена пароля{% endblock %}

{% block menu %}
    <li><a href="{% url "accounts:detail" request.user.pk %}">Назад</a></li>
    <li><a href="{% url "accounts:change" request.user.pk %}">Редактирование личных данных</a></li>
{% endblock %}

{% block content %}
    <h1>Смена пароля</h1>
    {% url "accounts:password_change" as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method="post" %}
{% endblock %}