source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

source/api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import AddFavoriteView, RemoveFavoritesView

app_name = 'api'

urlpatterns = [
    path('add_favorites/<int:pk>/', AddFavoriteView.as_view(), name='add_favorites'),
    path('remove_favorites/<int:pk>/', RemoveFavoritesView.as_view(), name='remove_favorites'),

]

source/main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api.urls')),
    path('', include('webapp.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

source/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, PhotoDetailView, PhotoCreateView, PhotoUpdateView, ProductDeleteView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('photo/<int:pk>/', PhotoDetailView.as_view(), name='photo_view'),
    path('photo_create/', PhotoCreateView.as_view(), name='photo_create'),
    path('photo_update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
    path('photo_delete/<int:pk>/', ProductDeleteView.as_view(), name='photo_delete')
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
# Фотография - картинка, обязательное;
# Подпись - строка, обязательное;
# Дата-время создания - проставляется автоматически;
# Автор - пользователь, обязательное


class Photo(models.Model):
    image = models.ImageField(upload_to='gallery_images', verbose_name='Фото')
    signature = models.CharField(max_length=200, verbose_name='Подпись')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    author = models.ForeignKey(get_user_model(), null=True, blank=True, on_delete=models.CASCADE,
                             related_name='author_photo', verbose_name='Автор Фотографии')


    def favorites_by(self, user):
        favorits= self.photo.filter(user=user)
        return favorits


    def __str__(self):
        return self.signature

    class Meta:
        verbose_name = 'Фото'
        verbose_name_plural = 'Фотографии'


class Favorites(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                             related_name='user_favorites', verbose_name='Пользователь', )
    photo = models.ForeignKey('webapp.Photo', on_delete=models.CASCADE,
                                related_name='photo', verbose_name='Фото')


    def __str__(self):
        return f'{self.user.username} - {self.photo.signature}'

    class Meta:
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранные'

source/webapp/forms.py
from django import forms
from webapp.models import Photo


class PhotoCreateForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ['image', 'signature']


class PhotoForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ['image', 'signature', 'author']

source/webapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.forms import PhotoForm, PhotoCreateForm
from webapp.models import Photo


class IndexView(ListView):
    template_name = 'photo/index.html'
    model = Photo
    context_object_name = 'photos'
    paginate_by = 5
    paginate_orphans = 0

    def get_queryset(self):
        data = Photo.objects.all()
        data.order_by('-created_at')
        return data


class PhotoDetailView(DetailView):
    template_name = 'photo/photo_view.html'
    context_object_name = 'photo'
    model = Photo
    pk_url_kwarg = 'pk'

    def get_success_url(self):
        return reverse('webapp:photo_detail')


class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    form_class = PhotoCreateForm
    template_name = 'photo/photo_create.html'
    permission_required = 'webapp.add_photo'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:photo_view', kwargs={'pk': self.object.pk})


class PhotoUpdateView(PermissionRequiredMixin, UpdateView):
    model = Photo
    form_class = PhotoCreateForm
    template_name = 'photo/product_update.html'
    permission_required = 'webapp.change_product'

    def test_func(self):
        photo = self.get_object()
        return self.request.user == photo.author or self.request.user.is_superuser \
               or self.request.user.has_perm('webapp.change_photo')

    def get_success_url(self):
        return reverse('webapp:photo_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    model = Photo
    template_name = 'photo/photo_delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_photo'

    def test_func(self):
        photo = self.get_object()
        return self.request.user == photo.author or self.request.user.is_superuser \
               or self.request.user.has_perm('webapp.delete_photo')


# class PhotoFavoritesAddView(LoginRequiredMixin, View):
#     def get(self, request, *args, **kwargs):
#         article = get_object_or_404(Photo, pk=kwargs.get('pk'))
        # like, created = ArticleLike.objects.get_or_create(article=article, user=request.user)
        # if created:
        #     article.like_count += 1
        #     article.save()
        #     return HttpResponse(article.like_count)
        # else:
        #     return HttpResponseForbidden()


# class PhotoFavoritesDellView(LoginRequiredMixin, View):
#     def get(self, request, *args, **kwargs):
#         article = get_object_or_404(Photo, pk=kwargs.get('pk'))
        # like = get_object_or_404(article.likes, user=request.user)
        # like.delete()
        # article.like_count -= 1
        # article.save()
        # return HttpResponse(article.like_count)

source/webapp/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Галерея{% endblock %}</title>

    <link rel="stylesheet" href="{% static "bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    {#                    <a class="nav-link" href="{% url 'webapp:index_project' %}">Главная <span#}
                    {#                            class="sr-only">(current)</span></a>#}
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'webapp:index' %}">Главная<span
                            class="sr-only">(current)</span></a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'webapp:photo_create' %}">Добавить Фото<span
                                class="sr-only">(current)</span></a>
                    </li>
                    {% block menu %}
                    {% endblock %}

                    <li><a class="nav-link"
                           href="{% url 'accounts:logout' %}">Logout</a></li>
                    <li><a class="nav-link"
                           href="{% url 'accounts:detail' request.user.pk %}">Привет, {{ request.user.get_full_name|default:request.user.username }}</a>
                    </li>
                {% else %}
                    <li><a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li><a class="nav-link" href="{% url 'accounts:create' %}">Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>
<div class="container">
    {% block content %}

    {% endblock %}
    <script src="{% static "js/index.js" %}"></script>
</div>
</body>
</html>




{#{% load staticfiles %}#}
{#<!doctype html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <meta name="viewport"#}
{#          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">#}
{#    <meta http-equiv="X-UA-Compatible" content="ie=edge">#}
{#    <title>{% block title %}My Site{% endblock %}</title>#}
{##}
{#    <!-- XDSoft DateTimePicker -->#}
{#    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />#}
{##}
{#    <link rel="stylesheet" href="{% static 'css/style.css' %}">#}
{#    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootswatch/4.5.0/sketchy/bootstrap.min.css"#}
{#          integrity="sha384-NkI/Nlr1DZ5rUXWWdnuZb97FQRgCCcwC66DC+HUCY0oVx6BgBHUfPcwL1vwp93JZ" crossorigin="anonymous">#}
{#    {% block links %}{% endblock %}#}
{#</head>#}
{#<body><div class="container">#}
{#<header>#}
{#<nav class="navbar navbar-expand-lg navbar-light bg-light">#}
{#  <a class="navbar-brand" href="{% url 'webapp:index' %}">Home</a>#}
{#    <a class="navbar-brand" href="{% url 'webapp:photo_create' %}">Добавить Фото</a>#}
{#    <a class="navbar-brand" href="{% url 'webapp:index' %}">Home</a>#}
{#    <a class="navbar-brand" href="{% url 'webapp:index' %}">Home</a>#}
{#  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">#}
{#    <span class="navbar-toggler-icon"></span>#}
{#  </button>#}
{#  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">#}
{#    <div class="navbar-nav">#}
{#      <a class="nav-link active" href="{% url 'webapp:index' %}">Home <span class="sr-only">(current)</span></a>#}
{#      <a class="nav-link" href="#">Features</a>#}
{#      <a class="nav-link" href="#">Pricing</a>#}
{#      <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>#}
{#    </div>#}
{#  </div>#}
{#</nav>#}
{##}
{##}
{##}
{##}
{#    <nav class="navbar navbar-expand-lg navbar-light bg-light">#}
{#        <div class="collapse navbar-collapse" id="navbarSupportedContent">#}
{#            <ul class="navbar-nav mr-auto">#}
{#                <li class="nav-item active">#}
{#                    <a class="nav-link" href="{% url 'webapp:index' %}">Главная <span#}
{#                            class="sr-only">(current)</span></a>#}
{#                </li>#}
{#                <li class="nav-item active">#}
{#                    <a class="nav-link" href="{% url 'webapp:index' %}">Главная<span#}
{#                            class="sr-only">(current)</span></a>#}
{#                </li>#}
{#                {% if request.user.is_authenticated %}#}
{#                    {% if perms.webapp.add_product %}#}
{#                        <li class="nav-item active">#}
{#                            <a class="nav-link" href="{% url 'webapp:product_create' %}">Добавить продукт<span#}
{#                                    class="sr-only">(current)</span></a>#}
{#                        </li>#}
{#                    {% endif %}#}
{#                {% block menu %}#}
{#                {% endblock %}#}
{#                    <li><a class="nav-link"#}
{#                           href="{% url 'accounts:logout' %}?next={{ request.get_full_path }}">Logout</a></li>#}
{#                    <li><a class="nav-link" href="{% url 'accounts:detail' request.user.pk %}">Привет, {{ request.user.get_full_name|default:request.user.username }}</a></li>#}
{#                {% else %}#}
{#                    {% if request.GET.next %}#}
{#                        <li><a class="nav-link" href="{% url 'accounts:login' %}?next={{ request.GET.next }}">Login</a>#}
{#                        </li>#}
{#                        <li><a class="nav-link" href="{% url 'accounts:create' %}?next={{ request.GET.next }}">Регистрация</a>#}
{#                        </li>#}
{#                    {% else %}#}
{#                        <li><a class="nav-link"#}
{#                               href="{% url 'accounts:login' %}?next={{ request.get_full_path }}">Login</a></li>#}
{#                        <li><a class="nav-link" href="{% url 'accounts:create' %}?next={{ request.get_full_path }}">Регистрация</a>#}
{#                        </li>#}
{#                    {% endif %}#}
{#                {% endif %}#}
{#            </ul>#}
{#        </div>#}
{#    </nav>#}
{#</header>#}
{#    {% block content %}{% endblock %}#}
{#    </div>#}
{#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>#}
{#    {% block scripts %}{% endblock %}#}
{#</body>#}
{#</html>#}