source/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import RegisterView, RegisterActivateView, UserDetailView, \
    UserChangeView, UserPasswordChangeView, UserPasswordResetEmailView, UserPasswordResetView

app_name = 'accounts'

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='create'),
    path('activate/<uuid:token>/', RegisterActivateView.as_view(), name='activate'),
    path('<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', UserChangeView.as_view(), name='change'),
    path('password-change/', UserPasswordChangeView.as_view(), name='password_change'),
    path('password-reset/', UserPasswordResetEmailView.as_view(), name='password_reset_email'),
    path('password-reset/<uuid:token>/', UserPasswordResetView.as_view(), name='password_reset')
]

source/api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import AddFavoriteView, RemoveFavoritesView

app_name = 'api'

urlpatterns = [
    path('add_favorites/<int:pk>/', AddFavoriteView.as_view(), name='add_favorites'),
    path('remove_favorites/<int:pk>/', RemoveFavoritesView.as_view(), name='remove_favorites'),

]

source/main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api.urls')),
    path('', include('webapp.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

source/webapp/urls.py
from django.urls import path

from webapp.views import IndexView, PhotoDetailView, PhotoCreateView, PhotoUpdateView, ProductDeleteView

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('photo/<int:pk>/', PhotoDetailView.as_view(), name='photo_view'),
    path('photo_create/', PhotoCreateView.as_view(), name='photo_create'),
    path('photo_update/<int:pk>/', PhotoUpdateView.as_view(), name='photo_update'),
    path('photo_delete/<int:pk>/', ProductDeleteView.as_view(), name='photo_delete')
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models
# Фотография - картинка, обязательное;
# Подпись - строка, обязательное;
# Дата-время создания - проставляется автоматически;
# Автор - пользователь, обязательное


class Photo(models.Model):
    image = models.ImageField(upload_to='gallery_images', verbose_name='Фото')
    signature = models.CharField(max_length=200, verbose_name='Подпись')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')
    author = models.ForeignKey(get_user_model(), null=True, blank=True, on_delete=models.CASCADE,
                             related_name='author_photo', verbose_name='Автор Фотографии')


    def favorites_by(self, user):
        favorits= self.photo.filter(user=user)
        return favorits


    def __str__(self):
        return self.signature

    class Meta:
        verbose_name = 'Фото'
        verbose_name_plural = 'Фотографии'


class Favorites(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                             related_name='user_favorites', verbose_name='Пользователь', )
    photo = models.ForeignKey('webapp.Photo', on_delete=models.CASCADE,
                                related_name='photo', verbose_name='Фото')


    def __str__(self):
        return f'{self.user.username} - {self.photo.signature}'

    class Meta:
        verbose_name = 'Избранное'
        verbose_name_plural = 'Избранные'

source/webapp/forms.py
from django import forms
from webapp.models import Photo


class PhotoCreateForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ['image', 'signature']


class PhotoForm(forms.ModelForm):

    class Meta:
        model = Photo
        fields = ['image', 'signature', 'author']

source/webapp/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views import View
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from webapp.forms import PhotoForm, PhotoCreateForm
from webapp.models import Photo


class IndexView(ListView):
    template_name = 'photo/index.html'
    model = Photo
    context_object_name = 'photos'
    paginate_by = 5
    paginate_orphans = 0

    def get_queryset(self):
        data = Photo.objects.all()
        data.order_by('-created_at')
        return data


class PhotoDetailView(DetailView):
    template_name = 'photo/photo_view.html'
    context_object_name = 'photo'
    model = Photo
    pk_url_kwarg = 'pk'

    def get_success_url(self):
        return reverse('webapp:photo_detail')


class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    form_class = PhotoCreateForm
    template_name = 'photo/photo_create.html'
    permission_required = 'webapp.add_photo'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:photo_view', kwargs={'pk': self.object.pk})


class PhotoUpdateView(PermissionRequiredMixin, UpdateView):
    model = Photo
    form_class = PhotoCreateForm
    template_name = 'photo/product_update.html'
    permission_required = 'webapp.change_product'

    def test_func(self):
        photo = self.get_object()
        return self.request.user == photo.author or self.request.user.is_superuser \
               or self.request.user.has_perm('webapp.change_photo')

    def get_success_url(self):
        return reverse('webapp:photo_view', kwargs={'pk': self.object.pk})


class ProductDeleteView(PermissionRequiredMixin, DeleteView):
    model = Photo
    template_name = 'photo/photo_delete.html'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_photo'

    def test_func(self):
        photo = self.get_object()
        return self.request.user == photo.author or self.request.user.is_superuser \
               or self.request.user.has_perm('webapp.delete_photo')


# class PhotoFavoritesAddView(LoginRequiredMixin, View):
#     def get(self, request, *args, **kwargs):
#         article = get_object_or_404(Photo, pk=kwargs.get('pk'))
        # like, created = ArticleLike.objects.get_or_create(article=article, user=request.user)
        # if created:
        #     article.like_count += 1
        #     article.save()
        #     return HttpResponse(article.like_count)
        # else:
        #     return HttpResponseForbidden()


# class PhotoFavoritesDellView(LoginRequiredMixin, View):
#     def get(self, request, *args, **kwargs):
#         article = get_object_or_404(Photo, pk=kwargs.get('pk'))
        # like = get_object_or_404(article.likes, user=request.user)
        # like.delete()
        # article.like_count -= 1
        # article.save()
        # return HttpResponse(article.like_count)

source/webapp/templates/photo/index.html
{% extends 'base.html' %}
{% load favorites_by %}
{% load staticfiles %}
{% block menu %}
{% endblock %}
{% block content %}
{% if is_paginated %}
    {% include 'partial/pagination.html' %}
{% endif %}
<h1>Галерея!</h1>
{% csrf_token %}
<div class="row row-cols-1 row-cols-md-2 row-cols-lg-3">

    {% for photo in photos %}
    <div class="col mb-6">
        <div class="card mb-5" style="width: 18rem;">
            <img src="{{ photo.image.url }}" class="card-img-top" height="300" alt="image">
            <div class="card-body">
                <h5 class="card-title">{{ photo.author }}</h5>
                <p class="card-text">{{ photo.signature }}</p>
                <p class="card-text"><small class="text-muted">{{ photo.created_at }}</small></p>
                <a href="{% url 'webapp:photo_view' photo.pk %}" class="btn btn-primary btn-block">Просмотр</a>
                {% if perms.webapp.change_photo or photo.author == request.user %}
                    <a href="{% url 'webapp:photo_update' photo.pk %}" class="btn btn-primary btn-block">Редактировать</a>
                {% endif %}
                {% if perms.webapp.delete_photo or photo.author == request.user %}
                    <a href="{% url 'webapp:photo_delete' photo.pk %}" class="btn btn-primary btn-block mb-2">Удалить</a>
                {% endif %}
                {% if user.is_authenticated %}
                    <p>


            {% with photo|favorites_by:user as favorites %}
                            <a class="btn btn-primary add btn-block" {% if favorites %}style="display: none"{% endif %} id="{{ photo.id }}" href="{% url 'api:add_favorites' photo.id %}">+</a>
                <a class="btn btn-primary remove btn-block " {% if not favorites %}style="display: none"{% endif %} id="{{ photo.id }}"
                   href="{% url 'api:remove_favorites' photo.id %}">-</a>
            {% endwith %}
                    {% endif %}
                </p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

source/webapp/templates/photo/photo_create.html
{% extends 'base.html' %}

{% block title %}Create{% endblock %}

{% block content %}
    <h1>Добавить фото</h1>

    {% url "webapp:photo_create" as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method='post'  enctype="multipart/form-data" %}
{% endblock %}

source/webapp/templates/photo/photo_delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:photo_view' product.pk %}">Отмена</a></li>
{% endblock %}

{% block content %}
    <h1>Вы уверены, что хотите удалить фото {{ photo.pk }}?</h1>
    <form action="{% url "webapp:photo_delete" photo.pk %}" method="post">
        {% csrf_token %}
        <p><input class=" btn btn-outline-dark btn-sm mb-1 mr-2 " type="submit" value="Да"></p>
        <p><a class=" btn btn-outline-dark btn-sm mb-1 mr-2" href="{% url 'webapp:photo_view' photo.pk %}">Отмена</a></p>
    </form>
{% endblock %}

source/webapp/templates/photo/photo_view.html
{% extends 'base.html' %}
{% block title %}View{% endblock %}

{% block menu %}
    {% if perms.webapp.change_photo or photo.author == request.user %}
        <li class="nav-item"><a class="nav-link" href="{% url 'webapp:photo_update' photo.pk %}">Update</a></li>
    {% endif %}
    {% if perms.webapp.delete_photo or photo.author == request.user %}

        <li class="nav-item"><a class="nav-link" href="{% url 'webapp:photo_delete' photo.pk %}">Delete</a></li>
    {% endif %}
{% endblock %}

{% block content %}
    <div class="box">
        <img src="{{ photo.image.url }}" class="card-img-top" alt="image">
{#        <h1>{{ photo.title }}</h1>#}
        <p class="pre">{{ photo.signature }}</p>
        <p>By:
            <a href="{% url 'accounts:detail' photo.author_id %}">{{ photo.author }}</a>
            | {{ photo.created_at|date:"d.m.Y H:i:s" }}
        </p>
{#        <p>Published at: {{ article.publish_at|date:"d.m.Y H:i:s" }}</p>#}
{#        <p>Tags: {% for tag in article.tags.all %}{{ tag.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>#}

    </div>
{% endblock %}

source/webapp/templates/photo/product_update.html
{% extends "base.html" %}

{% block title %}Update{% endblock %}

{% block menu %}
    <li><a href="{% url 'webapp:photo_view' photo.pk %}">Отмена</a></li>
{% endblock %}

{% block content %}
    <h1>Update Photo</h1>

    {% url "webapp:photo_update" pk=photo.pk as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method='post' enctype="multipart/form-data" button_text='Update' %}
{% endblock %}